### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by DaCao** [techno-express/node-unar#2]
I'm trying to use this package in my typescript project. 

```
John@MacBook-Pro:~/GAH/code/otto/api$ yarn start
yarn run v1.22.4
warning ../package.json: No license field
$ nodemon --exec ts-node --files src/index.ts
[nodemon] 2.0.8
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node --files src/index.ts`
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/John/GAH/code/otto/api/node_modules/node-unar/index.js
require() of ES modules is not supported.
require() of /Users/John/GAH/code/otto/api/node_modules/node-unar/index.js from /Users/John/GAH/code/otto/api/src/utils/decompress.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/John/GAH/code/otto/api/node_modules/node-unar/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/John/GAH/code/otto/api/src/utils/decompress.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/Users/John/GAH/code/otto/api/node_modules/ts-node/src/index.ts:530:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/John/GAH/code/otto/api/node_modules/ts-node/src/index.ts:533:12)
[nodemon] app crashed - waiting for file changes before starting...

```

How should I go on ?

**Comment by techno-express** [comment]
This package is ESM only, you using other packages not compatible, seems it expects common J's.
